# Site settings
title: Yenzichun's mystery box
email: yenping074@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You know less than you thought, and your memory is horrible.
#baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://yenzichun.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  yenzichun
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
comments: true
mathjax: true
