---
layout: post
title:  shiny and highcharts
date: "`r Sys.time()`"
published: true
tags: [example1, example2]
runtime: shiny
---


```{r include=FALSE}
library("shiny")
library("highcharter")
load(file = "ems_city_group_data.rda")
```

hear's a shiny app using highcharter package.

```{r, echo = FALSE}

shinyApp(
  ui = fluidPage(
  navbarPage( "EMS Project",
        tabPanel("tab 1",
                  wellPanel(
                    highchartOutput("hcontainer1")
                  )
        ),
        
        tabPanel("tab 2",
                 wellPanel(
                   highchartOutput("hcontainer2")
                 )
        )
  )      
),

# Server function
server = function(input, output, session) {
  require("highcharter")
  require("dplyr")
  l1 <- city_group_count %>% filter(yy==2007)
  l2 <- city_group_count %>% filter(yy==2008)
  l3 <- city_group_count %>% filter(yy==2009)
  l4 <- city_group_count %>% filter(yy==2010)
  l5 <- city_group_count %>% filter(yy==2011)
  l6 <- city_group_count %>% filter(yy==2012)
  l7 <- city_group_count %>% filter(yy==2013)
  citylist <- levels(as.factor(city_group_count$city2))
  
  yrlist <- paste0(levels(as.factor(city_group_count$yy)),"yr")
  Encoding(yrlist) <- "CP950" ## 轉成正常中文
  yrlist <- iconv(yrlist,"CP950","UTF-8")
  
  require("tidyr")
  y <- city_group_count %>% spread(.,city2,count)
  colnames(y) <- rep(letters,1,length(names(y)))
  
  output$hcontainer1 <- renderHighchart({
    
    highchart() %>%
      hc_chart(type = "column") %>%
      hc_title(text = "stacked column chart") %>%
      hc_xAxis( categories = citylist) %>%
      hc_yAxis( stackLabels = list( enabled = TRUE)) %>%
      hc_plotOptions( column = list( stacking = "normal")) %>%
      hc_add_series(name=yrlist[7],data = l7$count) %>%
      hc_add_series(name=yrlist[6],data = l6$count) %>%
      hc_add_series(name=yrlist[5],data = l5$count) %>%
      hc_add_series(name=yrlist[4],data = l4$count) %>%
      hc_add_series(name=yrlist[3],data = l3$count) %>%
      hc_add_series(name=yrlist[2],data = l2$count) %>%
      hc_add_series(name=yrlist[1],data = l1$count)
    
  })

  output$hcontainer2 <- renderHighchart({

    highchart() %>%
      hc_chart(type = "column") %>%
      hc_title(text = "stacked column chart") %>%
      hc_xAxis( categories = yrlist) %>%
      hc_yAxis( stackLabels = list( enabled = TRUE)) %>%
      hc_plotOptions( column = list( stacking = "normal")) %>%
      hc_add_series(name=citylist[1],data = y$b) %>%
      hc_add_series(name=citylist[2],data = y$c) %>%
      hc_add_series(name=citylist[3],data = y$d) %>%
      hc_add_series(name=citylist[4],data = y$e) %>%
      hc_add_series(name=citylist[5],data = y$f) %>%
      hc_add_series(name=citylist[6],data = y$g) %>%
      hc_add_series(name=citylist[7],data = y$h) %>%
      hc_add_series(name=citylist[8],data = y$i) %>%
      hc_add_series(name=citylist[9],data = y$j) %>%
      hc_add_series(name=citylist[10],data = y$k) %>%
      hc_add_series(name=citylist[11],data = y$l) %>%
      hc_add_series(name=citylist[12],data = y$m) %>%
      hc_add_series(name=citylist[13],data = y$n) %>%
      hc_add_series(name=citylist[14],data = y$o) %>%
      hc_add_series(name=citylist[15],data = y$p) %>%
      hc_add_series(name=citylist[16],data = y$q) %>%
      hc_add_series(name=citylist[17],data = y$r) %>%
      hc_add_series(name=citylist[18],data = y$s) %>%
      hc_add_series(name=citylist[19],data = y$t) %>%
      hc_add_series(name=citylist[20],data = y$u) %>%
      hc_add_series(name=citylist[21],data = y$v) %>%
      hc_add_series(name=citylist[22],data = y$w)

  })
},
options = list(height = 600)
  
)
```
